USE DATABASE INSURANCE_DW;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_CLAIM_ANALYTICS_BASE AS
SELECT
    -- Claim identifiers
    fc.CLAIM_KEY,
    fc.CLAIM_NUMBER,

    -- Customer
    dc.CUSTOMER_KEY,
    dc.CUSTOMER_NUMBER,
    dc.FIRST_NAME,
    dc.LAST_NAME,
    dc.CITY,
    dc.STATE,

    -- Policy
    dp.POLICY_KEY,
    dp.POLICY_NUMBER,
    dp.POLICY_TYPE,
    dp.POLICY_STATUS,
    dp.PREMIUM,

    -- Claim type
    dct.CLAIM_TYPE_KEY,
    dct.CLAIM_TYPE_CODE,
    dct.CLAIM_TYPE_NAME,

    -- Incident date
    incident_date.DATE_KEY AS INCIDENT_DATE_KEY,
    incident_date.FULL_DATE AS INCIDENT_DATE,
    incident_date.MONTH AS INCIDENT_MONTH,
    incident_date.MONTH_NAME AS INCIDENT_MONTH_NAME,
    incident_date.QUARTER AS INCIDENT_QUARTER,
    incident_date.YEAR AS INCIDENT_YEAR,

    -- Submitted date
    submitted_date.DATE_KEY AS SUBMITTED_DATE_KEY,
    submitted_date.FULL_DATE AS SUBMITTED_DATE,
    submitted_date.MONTH AS SUBMITTED_MONTH,
    submitted_date.YEAR AS SUBMITTED_YEAR,

    -- Settlement date
    settlement_date.DATE_KEY AS SETTLEMENT_DATE_KEY,
    settlement_date.FULL_DATE AS SETTLEMENT_DATE,
    settlement_date.MONTH AS SETTLEMENT_MONTH,
    settlement_date.YEAR AS SETTLEMENT_YEAR,

    -- Claim lifecycle
    fc.CLAIM_STATUS,

    -- Financial measures
    fc.ESTIMATED_LOSS,
    fc.APPROVED_AMOUNT,
    fc.SETTLEMENT_AMOUNT,

    -- Operational measures
    fc.CLAIM_COUNT,
    fc.PROCESSING_DAYS,

    -- AI
    fc.AI_REVIEW_REQUIRED,

    -- Audit timestamps
    fc.CREATED_AT,
    fc.UPDATED_AT

FROM FACT_CLAIM fc

LEFT JOIN DIM_CUSTOMER dc
    ON fc.CUSTOMER_KEY = dc.CUSTOMER_KEY

LEFT JOIN DIM_POLICY dp
    ON fc.POLICY_KEY = dp.POLICY_KEY

LEFT JOIN DIM_CLAIM_TYPE dct
    ON fc.CLAIM_TYPE_KEY = dct.CLAIM_TYPE_KEY

LEFT JOIN DIM_DATE incident_date
    ON fc.INCIDENT_DATE_KEY = incident_date.DATE_KEY

LEFT JOIN DIM_DATE submitted_date
    ON fc.SUBMITTED_DATE_KEY = submitted_date.DATE_KEY

LEFT JOIN DIM_DATE settlement_date
    ON fc.SETTLEMENT_DATE_KEY = settlement_date.DATE_KEY;

CREATE OR REPLACE VIEW VW_CLAIMS_OVERVIEW AS
SELECT
    COUNT(*) AS TOTAL_CLAIMS,

    SUM(CLAIM_COUNT) AS CLAIM_COUNT,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(ESTIMATED_LOSS) AS AVG_ESTIMATED_LOSS,

    AVG(APPROVED_AMOUNT) AS AVG_APPROVED_AMOUNT,

    AVG(SETTLEMENT_AMOUNT) AS AVG_SETTLEMENT_AMOUNT,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS,

    COUNT_IF(AI_REVIEW_REQUIRED) AS AI_REVIEW_REQUIRED_CLAIMS,

    COUNT_IF(CLAIM_STATUS = 'SETTLED') AS SETTLED_CLAIMS

FROM VW_CLAIM_ANALYTICS_BASE;

CREATE OR REPLACE VIEW VW_CLAIMS_BY_TYPE AS
SELECT
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME,

    COUNT(*) AS TOTAL_CLAIMS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(ESTIMATED_LOSS) AS AVG_ESTIMATED_LOSS,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS,

    COUNT_IF(AI_REVIEW_REQUIRED) AS AI_REVIEW_REQUIRED_CLAIMS

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME

ORDER BY
    TOTAL_CLAIMS DESC;

CREATE OR REPLACE VIEW VW_CLAIMS_BY_STATUS AS
SELECT
    CLAIM_STATUS,

    COUNT(*) AS TOTAL_CLAIMS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    CLAIM_STATUS

ORDER BY
    TOTAL_CLAIMS DESC;

CREATE OR REPLACE VIEW VW_CLAIMS_MONTHLY_TREND AS
SELECT
    INCIDENT_YEAR,
    INCIDENT_MONTH,

    MIN(INCIDENT_DATE) AS MONTH_START,

    COUNT(*) AS TOTAL_CLAIMS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    INCIDENT_YEAR,
    INCIDENT_MONTH

ORDER BY
    INCIDENT_YEAR,
    INCIDENT_MONTH;

CREATE OR REPLACE VIEW VW_CLAIMS_BY_POLICY_TYPE AS
SELECT
    POLICY_TYPE,

    COUNT(*) AS TOTAL_CLAIMS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(ESTIMATED_LOSS) AS AVG_ESTIMATED_LOSS,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    POLICY_TYPE

ORDER BY
    TOTAL_CLAIMS DESC;

CREATE OR REPLACE VIEW VW_CLAIMS_PROCESSING_ANALYTICS AS
SELECT
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME,

    COUNT(*) AS TOTAL_CLAIMS,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS,

    MIN(PROCESSING_DAYS) AS MIN_PROCESSING_DAYS,

    MAX(PROCESSING_DAYS) AS MAX_PROCESSING_DAYS,

    COUNT_IF(PROCESSING_DAYS <= 3)
        AS CLAIMS_PROCESSED_WITHIN_3_DAYS,

    COUNT_IF(PROCESSING_DAYS <= 7)
        AS CLAIMS_PROCESSED_WITHIN_7_DAYS

FROM VW_CLAIM_ANALYTICS_BASE

WHERE PROCESSING_DAYS IS NOT NULL

GROUP BY
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME

ORDER BY
    AVG_PROCESSING_DAYS DESC;

CREATE OR REPLACE VIEW VW_CLAIMS_SETTLEMENT_ANALYTICS AS
SELECT
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME,

    COUNT(*) AS TOTAL_CLAIMS,

    COUNT_IF(
        SETTLEMENT_AMOUNT IS NOT NULL
    ) AS SETTLED_FINANCIAL_RECORDS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    DIV0(
        SUM(SETTLEMENT_AMOUNT),
        SUM(ESTIMATED_LOSS)
    ) AS SETTLEMENT_TO_ESTIMATED_RATIO

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME

ORDER BY
    TOTAL_SETTLEMENT_AMOUNT DESC;

CREATE OR REPLACE VIEW VW_CLAIMS_AI_ANALYTICS AS
SELECT
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME,

    COUNT(*) AS TOTAL_CLAIMS,

    COUNT_IF(
        AI_REVIEW_REQUIRED = TRUE
    ) AS HUMAN_REVIEW_REQUIRED,

    COUNT_IF(
        AI_REVIEW_REQUIRED = FALSE
    ) AS HUMAN_REVIEW_NOT_REQUIRED,

    DIV0(
        COUNT_IF(
            AI_REVIEW_REQUIRED = TRUE
        ),
        COUNT(*)
    ) AS HUMAN_REVIEW_RATE

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    CLAIM_TYPE_CODE,
    CLAIM_TYPE_NAME

ORDER BY
    HUMAN_REVIEW_REQUIRED DESC;

CREATE OR REPLACE VIEW VW_CUSTOMER_CLAIMS_ANALYTICS AS
SELECT
    CUSTOMER_NUMBER,

    FIRST_NAME,

    LAST_NAME,

    CITY,

    STATE,

    COUNT(*) AS TOTAL_CLAIMS,

    SUM(ESTIMATED_LOSS) AS TOTAL_ESTIMATED_LOSS,

    SUM(APPROVED_AMOUNT) AS TOTAL_APPROVED_AMOUNT,

    SUM(SETTLEMENT_AMOUNT) AS TOTAL_SETTLEMENT_AMOUNT,

    AVG(PROCESSING_DAYS) AS AVG_PROCESSING_DAYS,

    COUNT_IF(
        AI_REVIEW_REQUIRED = TRUE
    ) AS AI_REVIEW_REQUIRED_CLAIMS

FROM VW_CLAIM_ANALYTICS_BASE

GROUP BY
    CUSTOMER_NUMBER,
    FIRST_NAME,
    LAST_NAME,
    CITY,
    STATE

ORDER BY
    TOTAL_CLAIMS DESC;