# Generated by Django 6.0.8 on 2026-09-08 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('claim_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('THEFT', 'Theft'), ('NATURAL_DISASTER', 'Natural Disaster'), ('FIRE', 'Fire'), ('OTHER', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('DOCUMENT_PROCESSING', 'Document Processing'), ('UNDER_REVIEW', 'Under Review'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLEMENT_IN_PROGRESS', 'Settlement in Progress'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=40)),
                ('incident_date', models.DateField()),
                ('incident_description', models.TextField()),
                ('estimated_loss', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='policies.policy')),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('estimated_loss__gte', 0)), name='claim_estimated_loss_gte_zero'), models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), ('approved_amount__gte', 0), _connector='OR'), name='claim_approved_amount_gte_zero')],
            },
        ),
    ]
