# Generated by Django 6.0.8 on 2026-09-10 07:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('ACCIDENT', 'Accident'), ('THEFT', 'Theft'), ('NATURAL_DISASTER', 'Natural Disaster'), ('FIRE', 'Fire'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SUBMITTED', 'Claim Submitted'), ('DOCUMENT_PROCESSING_STARTED', 'Document Processing Started'), ('REVIEW_STARTED', 'Review Started'), ('ADDITIONAL_INFORMATION_REQUESTED', 'Additional Information Requested'), ('REVIEW_RESUMED', 'Review Resumed'), ('APPROVED', 'Claim Approved'), ('REJECTED', 'Claim Rejected'), ('SETTLEMENT_STARTED', 'Settlement Started'), ('SETTLED', 'Claim Settled'), ('CLOSED', 'Claim Closed')], max_length=50)),
                ('from_status', models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('DOCUMENT_PROCESSING', 'Document Processing'), ('UNDER_REVIEW', 'Under Review'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLEMENT_IN_PROGRESS', 'Settlement in Progress'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], max_length=40, null=True)),
                ('to_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('DOCUMENT_PROCESSING', 'Document Processing'), ('UNDER_REVIEW', 'Under Review'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Information Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SETTLEMENT_IN_PROGRESS', 'Settlement in Progress'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_reference', models.CharField(max_length=100, unique=True)),
                ('settled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_settlements',
            },
        ),
        migrations.CreateModel(
            name='ClaimDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='claims.claim')),
            ],
            options={
                'db_table': 'claim_document_requirements',
                'ordering': ['document_type'],
                'constraints': [models.UniqueConstraint(fields=('claim', 'document_type'), name='unique_claim_document_requirement')],
            },
        ),
    ]
