# Generated by Django 6.0.8 on 2026-09-17 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claimaianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAIMissingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('source', models.CharField(choices=[('BUSINESS_RULE', 'Business Rule'), ('AI_OBSERVATION', 'AI Observation')], max_length=30)),
                ('document_type', models.CharField(blank=True, default='', max_length=50)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_missing_information', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', 'source'], name='claim_ai_missing_source_idx')],
            },
        ),
    ]
