# Generated by Django 6.0.8 on 2026-09-17 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claimaimissinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimAIInconsistency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inconsistency_type', models.CharField(choices=[('DATE_DISCREPANCY', 'Date Discrepancy'), ('AMOUNT_DISCREPANCY', 'Amount Discrepancy'), ('IDENTIFIER_DISCREPANCY', 'Identifier Discrepancy'), ('DESCRIPTION_DISCREPANCY', 'Description Discrepancy'), ('CONFLICTING_INFORMATION', 'Conflicting Information'), ('OTHER', 'Other')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=20)),
                ('description', models.TextField()),
                ('source_documents', models.JSONField(blank=True, default=list)),
                ('requires_human_review', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_inconsistencies', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', 'is_resolved'], name='claim_ai_inconsistency_idx')],
            },
        ),
    ]
