from django.urls import path

from .views import (
    ClaimAIIntelligenceView,
    ClaimInconsistencyListView,
    DocumentExtractionDetailView,
    DocumentProcessingJobListView,
    DocumentProcessingStartView,
    DocumentChunkListView,
    DocumentChunkingView,
    DocumentEmbeddingView,
    DocumentSearchView,
    MissingDocumentIntelligenceView,
    RAGQueryView,
    ClaimAISummaryView,
    ClaimAISummaryDetailView,
    ClaimInconsistencyAnalysisView,
)


urlpatterns = [
    path(
        "documents/<int:document_id>/process/",
        DocumentProcessingStartView.as_view(),
        name="document-processing-start",
    ),
    path(
        "documents/<int:document_id>/processing-jobs/",
        DocumentProcessingJobListView.as_view(),
        name="document-processing-jobs",
    ),
    path(
        "documents/<int:document_id>/extraction/",
        DocumentExtractionDetailView.as_view(),
        name="document-extraction-detail",
    ),
    path(
        "documents/<int:document_id>/chunks/",
        DocumentChunkingView.as_view(),
        name="document-chunking",
    ),
    path(
        "documents/<int:document_id>/chunks/list/",
        DocumentChunkListView.as_view(),
        name="document-chunk-list",
    ),
    path(
        "documents/<int:document_id>/embeddings/",
        DocumentEmbeddingView.as_view(),
        name="document-embeddings",
    ),
    path(
        "search/",
        DocumentSearchView.as_view(),
        name="document-search",
    ),
    path(
        "rag/query/",
        RAGQueryView.as_view(),
        name="rag-query",
    ),
    path(
        "claims/<int:claim_id>/summary/",
        ClaimAISummaryView.as_view(),
        name="claim-ai-summary",
    ),
    path(
        "claims/<int:claim_id>/summary/detail/",
        ClaimAISummaryDetailView.as_view(),
        name="claim-ai-summary-detail",
    ),
    path(
        "claims/<int:claim_id>/missing-documents/",
        MissingDocumentIntelligenceView.as_view(),
        name="missing-document-intelligence",
    ),
    path(
        "claims/<int:claim_id>/inconsistencies/analyze/",
        ClaimInconsistencyAnalysisView.as_view(),
        name="claim-inconsistency-analysis",
    ),

    path(
        "claims/<int:claim_id>/inconsistencies/",
        ClaimInconsistencyListView.as_view(),
        name="claim-inconsistency-list",
    ),  
    path(
        "claims/<int:claim_id>/intelligence/",
        ClaimAIIntelligenceView.as_view(),
        name="claim-ai-intelligence",
    ),
]