# Generated by Django 6.0.8 on 2026-09-09 05:23

import apps.common.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(default=apps.common.identifiers.generate_policy_number, editable=False, max_length=20, unique=True),
        ),
    ]
