# Generated by Django 6.0.8 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='faiss_index_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
