# Generated by Django 6.0.8 on 2026-09-17 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_documentchunk_embedded_at_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentextraction',
            name='extraction_method',
            field=models.CharField(choices=[('TEXT', 'Direct Text Extraction'), ('OCR', 'Optical Character Recognition'), ('VISION', 'Visual Analysis'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentVisualAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=150)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visual_analysis', to='documents.claimdocument')),
            ],
        ),
    ]
